### ISSUE TITLE
Utiliser les codes pays iso comme clé 

### ISSUE THREAD

**Issue by mikaoelitiana** [Randriamitsiry/pays_preposition#1]
Au lieu d'utiliser les noms des pays comme clés, il est peut-être préférable d'utiliser les codes iso plus courts et plus conventionnels. http://www.atlas-monde.net/codes-iso/

**Comment by Randriamitsiry** [comment]
Bonne idée! j'ai juste pensé au problème du genre "bienvenue + madagascar"
Je crois que je vais ajouté les deux fonctionnalités en parallèle.
Merci
